name: Build Go app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
      - name: Display Go version
        run: go version
      - name: Build Go app
        run: cd dataframe && go build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v4
      - name: run tests
        run: cd tests && go test -coverprofile ../coverage-report.txt
      - name: HTML report
        run: go tool cover -html=coverage-report.txt
